### ISSUE TITLE
论文参考

### ISSUE THREAD

**Issue by bule66** [yukihikawa/RL-HH#1]
请问有没有相应的论文参考

**Comment by yukihikawa** [comment]
今年的毕业设计，还在审呢。

**Comment by bule66** [comment]
> 今年的毕业设计，还在审呢。
同学，请问是这个方法不适用于超启发，还是不适用这个问题？

**Comment by yukihikawa** [comment]
用超启发式解FJSP肯定是没问题的，有很多设计思路。
具体到我这边，基本框架是选择超启发式，在我的具体实现中，这个框架下用强化学习作为高层的选择策略来选择LLH，效果就比较一般，因为超启发式的思想下能给到智能体的状态信息很少，而且因为启发式操作的随机性，执行操作后的奖励反馈不太稳定。
当然不是说强化学习就一定不能用，你可以考虑一下有没有更好的结合方法。
另外超启发式算法求解FJSP，影响效果的因素有很多，比如编码方式我用的AB串编码，可能析取图编码效果要更好；还有LLH和局部搜索的邻域设计，都是重要的影响因素。
